baseurl: ""

languages: ["de", "en"]
exclude_from_localizations: ["CNAME", "README.md", "LICENSE", "css", "images", "fonts"]
default_locale_in_subfolder: true
defaultLang: de
languageNames:
  de: Deutsch
  en: English

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "images/small"
    values:
      image: true

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  style: compressed

collections:
  people:
    output: true
  rules-and-habits:
    output: false
  products:
    output: true
  snapshots:
    output: false
#   feed:
#     output: true
#   checkItOut:
#     output: false

plugins:
  #  - jekyll-paginate
  #  - jekyll-sitemap
  - jekyll-image-size
  - jekyll-multiple-languages-plugin

exclude:
  - Gemfile
  - Gemfile.lock
  - docker-compose.yml
  - package.json
  - package-lock.json
  - raw-images

