# config.yml
local_backend: true

backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: 'src/assets/uploads'

collections:
  - name: 'skills'
    label: 'Leistungen von A-Z'
    folder: '_skills'
    create: true
    sortable_fields: ['title']
    editor:
      preview: false
    fields:
      - { label: 'Name der Leistung', name: 'title', widget: 'string' }
      - { label: 'Beschreibung', name: 'body', widget: 'markdown' }
